USE [master]
GO

/****** Object:  Database [BikeRental]    Script Date: 4/21/2020 5:04:24 PM ******/
CREATE DATABASE [BikeRental]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BikeRental', FILENAME = N'C:\Users\fsant\BikeRental.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BikeRental_log', FILENAME = N'C:\Users\fsant\BikeRental_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BikeRental].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BikeRental] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BikeRental] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BikeRental] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BikeRental] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BikeRental] SET ARITHABORT OFF 
GO

ALTER DATABASE [BikeRental] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BikeRental] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BikeRental] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BikeRental] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BikeRental] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BikeRental] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BikeRental] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BikeRental] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BikeRental] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BikeRental] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BikeRental] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BikeRental] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BikeRental] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BikeRental] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BikeRental] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BikeRental] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BikeRental] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BikeRental] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BikeRental] SET  MULTI_USER 
GO

ALTER DATABASE [BikeRental] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BikeRental] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BikeRental] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BikeRental] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BikeRental] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BikeRental] SET QUERY_STORE = OFF
GO

USE [BikeRental]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [BikeRental] SET  READ_WRITE 
GO

